/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package reconciler

import (
	"context"
	"fmt"

	appsv1 "k8s.io/api/apps/v1"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/equality"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"

	supabasev1alpha1 "github.com/supabase-community/supabase-kubernetes/api/v1alpha1"
)

// Result represents the outcome of an EnsureResource call.
type Result string

const (
	// ResultCreated indicates the resource was created.
	ResultCreated Result = "Created"
	// ResultUpdated indicates the resource was updated.
	ResultUpdated Result = "Updated"
	// ResultUnchanged indicates the resource was already up to date.
	ResultUnchanged Result = "Unchanged"
	// ResultDeleted indicates the resource was deleted.
	ResultDeleted Result = "Deleted"
)

// EnsureResource guarantees that the desired resource exists in the cluster.
// If the resource does not exist, it is created.
// If the resource exists, mutateFn is called with:
//   - existing: the object loaded from the cluster
//   - desired:  a copy of the object originally passed by the controller
//
// The object is then updated only when the mutated object is not already
// satisfied by the cluster object. This uses Semantic.DeepDerivative so that
// API-server defaults (e.g. ClusterIP on Services, strategy on Deployments)
// are ignored when deciding whether an update is needed.
// When owner is not nil, SetControllerReference is applied automatically.
func EnsureResource[T client.Object](
	ctx context.Context,
	c client.Client,
	desired T,
	owner client.Object,
	mutateFn func(existing, desired T) error,
) (Result, error) {
	if owner != nil {
		if err := controllerutil.SetControllerReference(owner, desired, c.Scheme()); err != nil {
			return "", fmt.Errorf("setting owner reference: %w", err)
		}
	}

	// Keep a copy of the original desired state so the mutateFn can compare
	// against the object as generated by the controller.
	original := desired.DeepCopyObject().(T)

	// Try to fetch the current object from the cluster.
	existing := desired.DeepCopyObject().(T)
	if err := c.Get(ctx, client.ObjectKeyFromObject(desired), existing); err != nil {
		if !apierrors.IsNotFound(err) {
			return "", err
		}

		// Resource does not exist: apply mutations and create it.
		if err := mutateFn(desired, original); err != nil {
			return "", err
		}
		if err := c.Create(ctx, desired); err != nil {
			return "", err
		}
		return ResultCreated, nil
	}

	// Resource exists: apply mutations to a copy of the cluster object.
	mutated := existing.DeepCopyObject().(T)
	if err := mutateFn(mutated, original); err != nil {
		return "", err
	}

	// If the cluster object already satisfies the mutated object (ignoring
	// server-side defaults), no update is necessary.
	if equality.Semantic.DeepEqual(mutated, existing) {
		return ResultUnchanged, nil
	}

	if err := c.Update(ctx, mutated); err != nil {
		return "", err
	}
	return ResultUpdated, nil
}

// DeleteResourceIfExists removes the resource from the cluster if it is present.
// NotFound errors are ignored so the operation is idempotent.
func DeleteResourceIfExists(ctx context.Context, c client.Client, obj client.Object) error {
	if err := c.Delete(ctx, obj); err != nil {
		if apierrors.IsNotFound(err) {
			return nil
		}
		return err
	}
	return nil
}

// DeleteConfigMapIfExists deletes a ConfigMap by name and namespace if it exists.
func DeleteConfigMapIfExists(ctx context.Context, c client.Client, name, namespace string) error {
	return DeleteResourceIfExists(ctx, c, &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace},
	})
}

// DeleteSecretIfExists deletes a Secret by name and namespace if it exists.
func DeleteSecretIfExists(ctx context.Context, c client.Client, name, namespace string) error {
	return DeleteResourceIfExists(ctx, c, &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace},
	})
}

// DeleteServiceIfExists deletes a Service by name and namespace if it exists.
func DeleteServiceIfExists(ctx context.Context, c client.Client, name, namespace string) error {
	return DeleteResourceIfExists(ctx, c, &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace},
	})
}

// DeletePersistentVolumeClaimIfExists deletes a PVC by name and namespace if it exists.
func DeletePersistentVolumeClaimIfExists(ctx context.Context, c client.Client, name, namespace string) error {
	return DeleteResourceIfExists(ctx, c, &corev1.PersistentVolumeClaim{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace},
	})
}

// DeleteStatefulSetIfExists deletes a StatefulSet by name and namespace if it exists.
func DeleteStatefulSetIfExists(ctx context.Context, c client.Client, name, namespace string) error {
	return DeleteResourceIfExists(ctx, c, &appsv1.StatefulSet{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace},
	})
}

// DeleteJobIfExists deletes a Job by name and namespace if it exists.
func DeleteJobIfExists(ctx context.Context, c client.Client, name, namespace string) error {
	return DeleteResourceIfExists(ctx, c, &batchv1.Job{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace},
	})
}

// DeleteDeploymentIfExists deletes a Deployment by name and namespace if it exists.
func DeleteDeploymentIfExists(ctx context.Context, c client.Client, name, namespace string) error {
	return DeleteResourceIfExists(ctx, c, &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace},
	})
}

// DeleteMigrationIfExists deletes a Migration by name and namespace if it exists.
func DeleteMigrationIfExists(ctx context.Context, c client.Client, name, namespace string) error {
	return DeleteResourceIfExists(ctx, c, &supabasev1alpha1.Migration{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace},
	})
}
