{{- if .Values.deployment.db.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "supabase.db.fullname" . }}-initdb
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  99-jwt.sql: |{{ .Files.Get "files/db/initdb/99-jwt.sql" | nindent 4 }}
  99-pooler.sql: |{{ .Files.Get "files/db/initdb/99-pooler.sql" | nindent 4 }}
  99-logs.sql: |{{ .Files.Get "files/db/initdb/99-logs.sql" | nindent 4 }}
  99-realtime.sql: |{{ .Files.Get "files/db/initdb/99-realtime.sql" | nindent 4 }}
  99-roles.sql: |{{ .Files.Get "files/db/initdb/99-roles.sql" | nindent 4 }}
  97-_supabase.sql: |{{ .Files.Get "files/db/initdb/97-_supabase.sql" | nindent 4 }}
  98-webhooks.sql: |{{ .Files.Get "files/db/initdb/98-webhooks.sql" | nindent 4 }}
{{- end }}
