apiVersion: core.supabase.io/v1alpha1
kind: Project
metadata:
  name: {{ include "supabase-project.fullname" . }}
  labels:
    {{- include "supabase-project.labels" . | nindent 4 }}
spec:
  databaseRef:
    kind: SingleDatabase
    name: {{ include "supabase-project.fullname" . | quote }}
  {{- .Values.project | toYaml | nindent 2 }}
