apiVersion: core.supabase.io/v1alpha1
kind: Project
metadata:
  name: {{ include "supabase-project.fullname" . }}
  labels:
    {{- include "supabase-project.labels" . | nindent 4 }}
spec:
  jwtExpSec: {{ .Values.project.jwtExpSec }}
  http:
    protocol: {{ .Values.project.http.protocol | quote }}
    hostname: {{ .Values.project.http.hostname | quote }}
    {{- with .Values.project.http.port }}
    port: {{ . }}
    {{- end }}
  databaseRef:
    kind: SingleDatabase
    name: {{ include "supabase-project.fullname" . | quote }}
  {{- with .Values.rest }}
  rest:
    enable: {{ .enable }}
    {{- with .replicas }}
    replicas: {{ . | int }}
    {{- end }}
    {{- with .pod }}
    pod:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .service }}
    service:
      {{- with .type }}
      type: {{ . | quote }}
      {{- end }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with .Values.meta }}
  meta:
    enable: {{ .enable }}
    {{- with .replicas }}
    replicas: {{ . | int }}
    {{- end }}
    {{- with .pod }}
    pod:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .service }}
    service:
      {{- with .type }}
      type: {{ . | quote }}
      {{- end }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with .Values.realtime }}
  realtime:
    enable: {{ .enable }}
    {{- with .replicas }}
    replicas: {{ . | int }}
    {{- end }}
    {{- with .pod }}
    pod:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .service }}
    service:
      {{- with .type }}
      type: {{ . | quote }}
      {{- end }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with .Values.auth }}
  auth:
    enable: {{ .enable }}
    {{- with .replicas }}
    replicas: {{ . | int }}
    {{- end }}
    {{- with .pod }}
    pod:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .service }}
    service:
      {{- with .type }}
      type: {{ . | quote }}
      {{- end }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with .Values.functions }}
  functions:
    enable: {{ .enable }}
    {{- with .replicas }}
    replicas: {{ . | int }}
    {{- end }}
    {{- with .pod }}
    pod:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .service }}
    service:
      {{- with .type }}
      type: {{ . | quote }}
      {{- end }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with .Values.envoy }}
  envoy:
    enable: {{ .enable }}
    {{- with .replicas }}
    replicas: {{ . | int }}
    {{- end }}
    {{- with .pod }}
    pod:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .service }}
    service:
      {{- with .type }}
      type: {{ . | quote }}
      {{- end }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- with .Values.storage }}
  storage:
    enable: {{ .enable }}
    {{- with .replicas }}
    replicas: {{ . | int }}
    {{- end }}
    {{- with .pod }}
    pod:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .service }}
    service:
      {{- with .type }}
      type: {{ . | quote }}
      {{- end }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    storage:
      accessModes:
        {{- toYaml .storage.accessModes | nindent 8 }}
      size: {{ .storage.size | quote }}
      {{- with .storage.storageClassName }}
      storageClassName: {{ . | quote }}
      {{- end }}
      {{- with .storage.deletionPolicy }}
      deletionPolicy: {{ . | quote }}
      {{- end }}
  {{- end }}
  {{- with .Values.studio }}
  studio:
    enable: {{ .enable }}
    {{- with .replicas }}
    replicas: {{ . | int }}
    {{- end }}
    {{- with .pod }}
    pod:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .service }}
    service:
      {{- with .type }}
      type: {{ . | quote }}
      {{- end }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    storage:
      accessModes:
        {{- toYaml .storage.accessModes | nindent 8 }}
      size: {{ .storage.size | quote }}
      {{- with .storage.storageClassName }}
      storageClassName: {{ . | quote }}
      {{- end }}
      {{- with .storage.deletionPolicy }}
      deletionPolicy: {{ . | quote }}
      {{- end }}
  {{- end }}
