apiVersion: core.supabase.io/v1alpha1
kind: SingleDatabase
metadata:
  name: {{ include "supabase-project.fullname" . }}
  labels:
    {{- include "supabase-project.labels" . | nindent 4 }}
spec:
  {{- .Values.singleDatabase | toYaml | nindent 2 }}
