{{- define "supabase.secret.bigquery.name" -}}
{{- if .Values.secret.bigquery.secretRef -}}
{{- .Values.secret.bigquery.secretRef -}}
{{- else -}}
{{- include "supabase.secret.bigquery" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.bigquery.key.gcloudJson" -}}
{{- index (default (dict) .Values.secret.bigquery.secretRefKey) "gcloudJson" | default "gcloud.json" -}}
{{- end -}}

{{- if and .Values.bigQuery.enabled (not .Values.secret.bigquery.secretRef) }}
{{- $existing := dict }}
{{- if .Values.secret.preserveExisting }}
{{- $existing = (get (lookup "v1" "Secret" .Release.Namespace (include "supabase.secret.bigquery" .)) "data") | default dict }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.bigquery" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- include "supabase.secret.keepAnnotation" . }}
type: Opaque
data:
  gcloud.json: {{ get $existing "gcloud.json" | default (.Values.secret.bigquery.gcloudJson | b64enc) | quote }}
{{- end }}
