{{- define "supabase.secret.db.name" -}}
{{- if .Values.secret.db.secretRef -}}
{{- .Values.secret.db.secretRef -}}
{{- else -}}
{{- include "supabase.secret.db" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.db.key.host" -}}
{{- index (default (dict) .Values.secret.db.secretRefKey) "host" | default "host" -}}
{{- end -}}

{{- define "supabase.secret.db.key.port" -}}
{{- index (default (dict) .Values.secret.db.secretRefKey) "port" | default "port" -}}
{{- end -}}

{{- define "supabase.secret.db.key.password" -}}
{{- index (default (dict) .Values.secret.db.secretRefKey) "password" | default "password" -}}
{{- end -}}

{{- define "supabase.secret.db.key.database" -}}
{{- index (default (dict) .Values.secret.db.secretRefKey) "database" | default "database" -}}
{{- end -}}

{{- define "supabase.secret.db.key.passwordEncoded" -}}
{{- if .Values.secret.db.secretRef -}}
{{- $keys := default (dict) .Values.secret.db.secretRefKey -}}
{{- index $keys "passwordEncoded" | default (index $keys "password") | default "password" -}}
{{- else -}}
password_encoded
{{- end -}}
{{- end -}}

{{- if not .Values.secret.db.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.db" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secret.db.password | b64enc | quote }}
  database: {{ .Values.secret.db.database | b64enc | quote }}
  password_encoded: {{ .Values.secret.db.password | urlquery | b64enc | quote }}
{{- end }}
