{{- define "supabase.secret.jwt.name" -}}
{{- if .Values.secret.jwt.secretRef -}}
{{- .Values.secret.jwt.secretRef -}}
{{- else -}}
{{- include "supabase.secret.jwt" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.jwt.key.anonKey" -}}
{{- index (default (dict) .Values.secret.jwt.secretRefKey) "anonKey" | default "anonKey" -}}
{{- end -}}

{{- define "supabase.secret.jwt.key.serviceKey" -}}
{{- index (default (dict) .Values.secret.jwt.secretRefKey) "serviceKey" | default "serviceKey" -}}
{{- end -}}

{{- define "supabase.secret.jwt.key.secret" -}}
{{- index (default (dict) .Values.secret.jwt.secretRefKey) "secret" | default "secret" -}}
{{- end -}}

{{- if not .Values.secret.jwt.secretRef }}
{{- $existing := dict }}
{{- if .Values.secret.preserveExisting }}
{{- $existing = (get (lookup "v1" "Secret" .Release.Namespace (include "supabase.secret.jwt" .)) "data") | default dict }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.jwt" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- include "supabase.secret.keepAnnotation" . }}
type: Opaque
data:
  anonKey: {{ get $existing "anonKey" | default (.Values.secret.jwt.anonKey | b64enc) | quote }}
  serviceKey: {{ get $existing "serviceKey" | default (.Values.secret.jwt.serviceKey | b64enc) | quote }}
  secret: {{ get $existing "secret" | default (.Values.secret.jwt.secret | b64enc) | quote }}
{{- end }}
