{{- define "supabase.secret.jwt.name" -}}
{{- if .Values.secret.jwt.secretRef -}}
{{- .Values.secret.jwt.secretRef -}}
{{- else -}}
{{- include "supabase.secret.jwt" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.jwt.key.anonKey" -}}
{{- index (default (dict) .Values.secret.jwt.secretRefKey) "anonKey" | default "anonKey" -}}
{{- end -}}

{{- define "supabase.secret.jwt.key.serviceKey" -}}
{{- index (default (dict) .Values.secret.jwt.secretRefKey) "serviceKey" | default "serviceKey" -}}
{{- end -}}

{{- define "supabase.secret.jwt.key.secret" -}}
{{- index (default (dict) .Values.secret.jwt.secretRefKey) "secret" | default "secret" -}}
{{- end -}}

{{- if not .Values.secret.jwt.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.jwt" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  anonKey: {{ .Values.secret.jwt.anonKey | b64enc | quote }}
  serviceKey: {{ .Values.secret.jwt.serviceKey | b64enc | quote }}
  secret: {{ .Values.secret.jwt.secret | b64enc | quote }}
{{- end }}
