{{- define "supabase.secret.realtime.name" -}}
{{- if .Values.secret.realtime.secretRef -}}
{{- .Values.secret.realtime.secretRef -}}
{{- else -}}
{{- include "supabase.secret.realtime" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.realtime.key.secretKeyBase" -}}
{{- index (default (dict) .Values.secret.realtime.secretRefKey) "secretKeyBase" | default "secretKeyBase" -}}
{{- end -}}

{{- if not .Values.secret.realtime.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.realtime" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  secretKeyBase: {{ .Values.secret.realtime.secretKeyBase | b64enc | quote }}
{{- end }}
