{{- define "supabase.secret.s3.name" -}}
{{- if .Values.secret.s3.secretRef -}}
{{- .Values.secret.s3.secretRef -}}
{{- else -}}
{{- include "supabase.secret.s3" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.s3.key.keyId" -}}
{{- index (default (dict) .Values.secret.s3.secretRefKey) "keyId" | default "keyId" -}}
{{- end -}}

{{- define "supabase.secret.s3.key.accessKey" -}}
{{- index (default (dict) .Values.secret.s3.secretRefKey) "accessKey" | default "accessKey" -}}
{{- end -}}

{{- define "supabase.secret.s3.key.password" -}}
{{- index (default (dict) .Values.secret.s3.secretRefKey) "password" | default "password" -}}
{{- end -}}

{{- if not .Values.secret.s3.secretRef }}
{{- $existing := dict }}
{{- if .Values.secret.preserveExisting }}
{{- $existing = (get (lookup "v1" "Secret" .Release.Namespace (include "supabase.secret.s3" .)) "data") | default dict }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.s3" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- include "supabase.secret.keepAnnotation" . }}
type: Opaque
data:
  keyId: {{ get $existing "keyId" | default (.Values.secret.s3.keyId | b64enc) | quote }}
  accessKey: {{ get $existing "accessKey" | default (.Values.secret.s3.accessKey | b64enc) | quote }}
{{- end }}
