{{- define "supabase.secret.s3.name" -}}
{{- if .Values.secret.s3.secretRef -}}
{{- .Values.secret.s3.secretRef -}}
{{- else -}}
{{- include "supabase.secret.s3" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.s3.key.keyId" -}}
{{- index (default (dict) .Values.secret.s3.secretRefKey) "keyId" | default "keyId" -}}
{{- end -}}

{{- define "supabase.secret.s3.key.accessKey" -}}
{{- index (default (dict) .Values.secret.s3.secretRefKey) "accessKey" | default "accessKey" -}}
{{- end -}}

{{- define "supabase.secret.s3.key.password" -}}
{{- index (default (dict) .Values.secret.s3.secretRefKey) "password" | default "password" -}}
{{- end -}}

{{- if not .Values.secret.s3.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.s3" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  keyId: {{ .Values.secret.s3.keyId | b64enc | quote }}
  accessKey: {{ .Values.secret.s3.accessKey | b64enc | quote }}
{{- end }}
