{{- define "supabase.secret.smtp.name" -}}
{{- if .Values.secret.smtp.secretRef -}}
{{- .Values.secret.smtp.secretRef -}}
{{- else -}}
{{- include "supabase.secret.smtp" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.smtp.key.username" -}}
{{- index (default (dict) .Values.secret.smtp.secretRefKey) "username" | default "username" -}}
{{- end -}}

{{- define "supabase.secret.smtp.key.password" -}}
{{- index (default (dict) .Values.secret.smtp.secretRefKey) "password" | default "password" -}}
{{- end -}}

{{- if not .Values.secret.smtp.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.smtp" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secret.smtp.username | b64enc | quote }}
  password: {{ .Values.secret.smtp.password | b64enc | quote }}
{{- end }}
