{{- define "supabase.secret.smtp.name" -}}
{{- if .Values.secret.smtp.secretRef -}}
{{- .Values.secret.smtp.secretRef -}}
{{- else -}}
{{- include "supabase.secret.smtp" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.smtp.key.username" -}}
{{- index (default (dict) .Values.secret.smtp.secretRefKey) "username" | default "username" -}}
{{- end -}}

{{- define "supabase.secret.smtp.key.password" -}}
{{- index (default (dict) .Values.secret.smtp.secretRefKey) "password" | default "password" -}}
{{- end -}}

{{- if not .Values.secret.smtp.secretRef }}
{{- $existing := dict }}
{{- if .Values.secret.preserveExisting }}
{{- $existing = (get (lookup "v1" "Secret" .Release.Namespace (include "supabase.secret.smtp" .)) "data") | default dict }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.smtp" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- include "supabase.secret.keepAnnotation" . }}
type: Opaque
data:
  username: {{ get $existing "username" | default (.Values.secret.smtp.username | b64enc) | quote }}
  password: {{ get $existing "password" | default (.Values.secret.smtp.password | b64enc) | quote }}
{{- end }}
