---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.supabase.io
  resources:
  - databasemigrations
  - externaldatabases
  - functions
  - projects
  - singledatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.supabase.io
  resources:
  - databasemigrations/finalizers
  - externaldatabases/finalizers
  - functions/finalizers
  - projects/finalizers
  - singledatabases/finalizers
  verbs:
  - update
- apiGroups:
  - core.supabase.io
  resources:
  - databasemigrations/status
  - externaldatabases/status
  - functions/status
  - projects/status
  - singledatabases/status
  verbs:
  - get
  - patch
  - update
