{{- if .Values.deployment.auth.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.auth.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.auth.enabled }}
  replicas: {{ .Values.deployment.auth.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.auth.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.auth.pullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.auth.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.auth.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-db
          image: "{{ .Values.image.initDb.repository }}:{{ .Values.image.initDb.tag }}"
          imagePullPolicy: {{ .Values.image.initDb.pullPolicy }}
          env:
            - name: DB_HOST
              {{- if .Values.deployment.db.enabled }}
              value: {{ include "supabase.db.fullname" . | quote }}
              {{- else if and .Values.secret.db.secretRef (hasKey (default (dict) .Values.secret.db.secretRefKey) "host") }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.host" . }}
              {{- else if .Values.secret.db.host }}
              value: {{ .Values.secret.db.host | quote }}
              {{- else }}
              value: {{ .Values.environment.auth.DB_HOST | quote }}
              {{- end }}
            - name: DB_PORT
              {{- if and (not .Values.deployment.db.enabled) .Values.secret.db.secretRef (hasKey (default (dict) .Values.secret.db.secretRefKey) "port") }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.port" . }}
              {{- else if and (not .Values.deployment.db.enabled) .Values.secret.db.port }}
              value: {{ .Values.secret.db.port | quote }}
              {{- else }}
              value: {{ .Values.environment.auth.DB_PORT | quote }}
              {{- end }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              until pg_isready -h $(DB_HOST) -p $(DB_PORT) -U postgres; do
              echo "Waiting for database to start..."
              sleep 2
              done
            - echo "Database is ready"
      containers:
        - name: {{ include "supabase.auth.name" $ }}
          securityContext:
            {{- toYaml .Values.deployment.auth.securityContext | nindent 12 }}
          image: "{{ .Values.image.auth.repository }}:{{ .Values.image.auth.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.auth.pullPolicy }}
          env:
            {{- range $key, $value := .Values.environment.auth }}
            {{- if not (and (not $.Values.deployment.db.enabled) (or (and (eq $key "DB_HOST") (or (and $.Values.secret.db.secretRef (hasKey (default (dict) $.Values.secret.db.secretRefKey) "host")) $.Values.secret.db.host)) (and (eq $key "DB_PORT") (or (and $.Values.secret.db.secretRef (hasKey (default (dict) $.Values.secret.db.secretRefKey) "port")) $.Values.secret.db.port)))) }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- if .Values.deployment.db.enabled }}
            - name: DB_HOST
              value: {{ include "supabase.db.fullname" . }}
            {{- else if and .Values.secret.db.secretRef (hasKey (default (dict) .Values.secret.db.secretRefKey) "host") }}
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.host" . }}
            {{- else if .Values.secret.db.host }}
            - name: DB_HOST
              value: {{ .Values.secret.db.host | quote }}
            {{- end }}
            {{- if and (not .Values.deployment.db.enabled) .Values.secret.db.secretRef (hasKey (default (dict) .Values.secret.db.secretRefKey) "port") }}
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.port" . }}
            {{- else if and (not .Values.deployment.db.enabled) .Values.secret.db.port }}
            - name: DB_PORT
              value: {{ .Values.secret.db.port | quote }}
            {{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.password" . }}
            - name: DB_PASSWORD_ENC
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.passwordEncoded" . }}
            - name: DB_NAME
              {{- if and .Values.secret.db.secretRef (not (hasKey (default (dict) .Values.secret.db.secretRefKey) "database")) }}
              value: {{ .Values.secret.db.database | default "postgres" | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.database" . }}
              {{- end }}
            - name: GOTRUE_DB_DATABASE_URL
              value: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD_ENC)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL)
            - name: GOTRUE_DB_DRIVER
              value: $(DB_DRIVER)
            - name: GOTRUE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.jwt.name" . }}
                  key: {{ include "supabase.secret.jwt.key.secret" . }}
            {{- if or .Values.secret.apikey.secretRef .Values.secret.apikey.jwtKeys }}
            - name: GOTRUE_JWT_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.apikey.name" . }}
                  key: {{ include "supabase.secret.apikey.key.jwtKeys" . }}
            {{- end }}
            - name: GOTRUE_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.smtp.name" . }}
                  key: {{ include "supabase.secret.smtp.key.username" . }}
            - name: GOTRUE_SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.smtp.name" . }}
                  key: {{ include "supabase.secret.smtp.key.password" . }}
          {{- with .Values.deployment.auth.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.auth.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.auth.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
          {{- with .Values.deployment.auth.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.auth.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.deployment.auth.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.auth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.auth.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
