{{- if .Values.deployment.auth.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.auth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.deployment.auth.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.auth.enabled }}
  replicas: {{ .Values.deployment.auth.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "supabase.auth.selectorLabels" . | nindent 8 }}
      {{- with .Values.deployment.auth.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "supabase.auth.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.deployment.auth.automountServiceAccountToken }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.deployment.auth.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.deployment.auth.podSecurityContext | nindent 8 }}
      {{- with .Values.image.auth.pullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.auth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.auth.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.auth.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      initContainers:
        - name: init-db
          image: "{{ .Values.image.initDb.repository }}:{{ .Values.image.initDb.tag }}"
          imagePullPolicy: {{ .Values.image.initDb.pullPolicy }}
          env:
            {{- include "supabase.db.hostEnv" (dict "root" . "name" "DB_HOST") | nindent 12 }}
            {{- include "supabase.db.portEnv" (dict "root" . "name" "DB_PORT") | nindent 12 }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              until pg_isready -h $(DB_HOST) -p $(DB_PORT) -U postgres; do
              echo "Waiting for database to start..."
              sleep 2
              done
            - echo "Database is ready"
      containers:
        - name: {{ include "supabase.auth.name" $ }}
          image: "{{ .Values.image.auth.repository }}:{{ .Values.image.auth.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.auth.pullPolicy }}
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
          env:
            {{- range $key, $value := .Values.environment.auth }}
            {{- if and (ne $key "DB_HOST") (ne $key "DB_PORT") }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- include "supabase.db.hostEnv" (dict "root" . "name" "DB_HOST") | nindent 12 }}
            {{- include "supabase.db.portEnv" (dict "root" . "name" "DB_PORT") | nindent 12 }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.password" . }}
            - name: DB_PASSWORD_ENC
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.passwordEncoded" . }}
            - name: DB_NAME
              {{- if and .Values.secret.db.secretRef (not (hasKey (default (dict) .Values.secret.db.secretRefKey) "database")) }}
              value: {{ .Values.secret.db.database | default "postgres" | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.database" . }}
              {{- end }}
            - name: GOTRUE_DB_DATABASE_URL
              value: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD_ENC)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL)
            - name: GOTRUE_DB_DRIVER
              value: $(DB_DRIVER)
            - name: GOTRUE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.jwt.name" . }}
                  key: {{ include "supabase.secret.jwt.key.secret" . }}
            {{- if or .Values.secret.apikey.secretRef .Values.secret.apikey.jwtKeys }}
            - name: GOTRUE_JWT_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.apikey.name" . }}
                  key: {{ include "supabase.secret.apikey.key.jwtKeys" . }}
            {{- end }}
            - name: GOTRUE_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.smtp.name" . }}
                  key: {{ include "supabase.secret.smtp.key.username" . }}
            - name: GOTRUE_SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.smtp.name" . }}
                  key: {{ include "supabase.secret.smtp.key.password" . }}
          {{- with .Values.deployment.auth.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.auth.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.auth.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.auth.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.auth.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.auth.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.auth.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.deployment.auth.securityContext | nindent 12 }}
      {{- with .Values.deployment.auth.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
