apiVersion: core.supabase.io/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: supabase-operator
    app.kubernetes.io/managed-by: kustomize
  name: project-sample
spec:
  version: "2026.04.27"

  global:
    siteUrl: "https://supabase.example.com"
    jwtExpirySeconds: 1800

  http:
    protocol: "http"
    hostname: "supabase.local"
    gatewayRef:
      name: "gw"
      namespace: "envoy-gateway-system"

  database:
    host: "postgres.db.svc.cluster.local"
    passwordRef:
      name: supabase-db-credentials
      key: password
