apiVersion: core.supabase.io/v1alpha1
kind: Project
metadata:
  labels:
    app.kubernetes.io/name: supabase-operator
    app.kubernetes.io/managed-by: kustomize
  name: project-sample
spec:
  global:
    siteUrl: "https://supabase.example.com"
  http:
    protocol: "http"
    hostname: "supabase.local"
    gatewayRef:
      name: "gw"
      namespace: "envoy-gateway-system"
  database:
    host: "postgres.db.svc.cluster.local"
    passwordRef:
      name: supabase-db-credentials
      key: password
  studio:
    image: "supabase/studio:2026.04.27-sha-5f60601"
  auth:
    image: "supabase/gotrue:v2.186.0"
    saml:
      enabled: true
    sms:
      provider: twilio
      template: "Your code {{ .Code }}"
      twilio:
        accountSidRef:
          name: supabase-db-credentials
          key: password
        authTokenRef:
          name: supabase-db-credentials
          key: password
        messageServiceSidRef:
          name: supabase-db-credentials
          key: password

    # disableSignup: true
    # oauth:
    #   azure:
    #     enabled: true
    #     clientIdRef:
    #       name: supabase-db-credentials
    #       key: password
    #     clientSecretRef:
    #       name: supabase-db-credentials
    #       key: password
    #   google:
    #     enabled: true
    #     clientIdRef:
    #       name: supabase-db-credentials
    #       key: password
    #     clientSecretRef:
    #       name: supabase-db-credentials
    #       key: password
    #   github:
    #     enabled: true
    #     clientIdRef:
    #       name: supabase-db-credentials
    #       key: password
    #     clientSecretRef:
    #       name: supabase-db-credentials
    #       key: password

    # email:
    #   enableSignup: false
    #   smtp:
    #     adminEmail: luiz@admin.com
    #     host: smtp.google.com
    #     passRef:
    #       name: supabase-db-credentials
    #       key: password
    #     port: 576
    #     userRef:
    #       name: supabase-db-credentials
    #       key: password

  rest:
    image: "postgrest/postgrest:v14.8"
  realtime:
    image: "supabase/realtime:v2.76.5"
  storage:
    image: "supabase/storage-api:v1.48.26"
  meta:
    image: "supabase/postgres-meta:v0.96.3"
  functions:
    image: "supabase/edge-runtime:v1.71.2"
