## Append samples of your project ##
resources:
  - singledatabase.yaml
  - migration.yaml
  - project.yaml
  - meta.yaml
  - rest.yaml
  - realtime.yaml
  - auth.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
