apiVersion: core.supabase.io/v1
kind: Project
metadata:
  name: supabase
spec:
  # jwtExpSec: 1800

  apiUrl: "http://api.supabase.local"

  databaseRef:
    kind: SingleDatabase
    name: supabase

  # migration defines the pod template for the initial Migration Job created by the Project.
  # migration:
  #   pod:
  #     spec:
  #       nodeSelector:
  #         workload: migrations
  #       tolerations:
  #         - key: "dedicated"
  #           operator: "Equal"
  #           value: "migrations"
  #           effect: "NoSchedule"
  #       containers:
  #         - name: migration
  #           resources:
  #             requests:
  #               cpu: 100m
  #               memory: 128Mi

  # syncJwtJob defines the pod template for the JWT sync Job created by the Project.
  # syncJwtJob:
  #   pod:
  #     spec:
  #       nodeSelector:
  #         workload: jobs
  #       containers:
  #         - name: sync-jwt
  #           resources:
  #             requests:
  #               cpu: 50m
  #               memory: 64Mi

  # syncPasswordJob defines the pod template for the password sync Job created by the Project.
  # syncPasswordJob:
  #   pod:
  #     spec:
  #       nodeSelector:
  #         workload: jobs
  #       containers:
  #         - name: sync-password
  #           resources:
  #             requests:
  #               cpu: 50m
  #               memory: 64Mi
