apiVersion: core.supabase.io/v1alpha1
kind: Storage
metadata:
  name: supabase
spec:
  projectRef:
    name: supabase
  replicas: 1
  storage:
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 5Gi
