//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthEmailSpec) DeepCopyInto(out *AuthEmailSpec) {
	*out = *in
	if in.EnableSignup != nil {
		in, out := &in.EnableSignup, &out.EnableSignup
		*out = new(bool)
		**out = **in
	}
	if in.AutoConfirm != nil {
		in, out := &in.AutoConfirm, &out.AutoConfirm
		*out = new(bool)
		**out = **in
	}
	if in.SMTP != nil {
		in, out := &in.SMTP, &out.SMTP
		*out = new(AuthSmtpSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthEmailSpec.
func (in *AuthEmailSpec) DeepCopy() *AuthEmailSpec {
	if in == nil {
		return nil
	}
	out := new(AuthEmailSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthMfaSpec) DeepCopyInto(out *AuthMfaSpec) {
	*out = *in
	if in.TOTPEnrollEnabled != nil {
		in, out := &in.TOTPEnrollEnabled, &out.TOTPEnrollEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TOTPVerifyEnabled != nil {
		in, out := &in.TOTPVerifyEnabled, &out.TOTPVerifyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PhoneEnrollEnabled != nil {
		in, out := &in.PhoneEnrollEnabled, &out.PhoneEnrollEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PhoneVerifyEnabled != nil {
		in, out := &in.PhoneVerifyEnabled, &out.PhoneVerifyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MaxEnrolledFactors != nil {
		in, out := &in.MaxEnrolledFactors, &out.MaxEnrolledFactors
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthMfaSpec.
func (in *AuthMfaSpec) DeepCopy() *AuthMfaSpec {
	if in == nil {
		return nil
	}
	out := new(AuthMfaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthOAuthSpec) DeepCopyInto(out *AuthOAuthSpec) {
	*out = *in
	if in.Google != nil {
		in, out := &in.Google, &out.Google
		*out = new(OAuthProviderSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(OAuthProviderSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(OAuthProviderSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthOAuthSpec.
func (in *AuthOAuthSpec) DeepCopy() *AuthOAuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthOAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthPhoneSpec) DeepCopyInto(out *AuthPhoneSpec) {
	*out = *in
	if in.EnableSignup != nil {
		in, out := &in.EnableSignup, &out.EnableSignup
		*out = new(bool)
		**out = **in
	}
	if in.AutoConfirm != nil {
		in, out := &in.AutoConfirm, &out.AutoConfirm
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthPhoneSpec.
func (in *AuthPhoneSpec) DeepCopy() *AuthPhoneSpec {
	if in == nil {
		return nil
	}
	out := new(AuthPhoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSamlSpec) DeepCopyInto(out *AuthSamlSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.PrivateKeyRef != nil {
		in, out := &in.PrivateKeyRef, &out.PrivateKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.AllowEncryptedAssertions != nil {
		in, out := &in.AllowEncryptedAssertions, &out.AllowEncryptedAssertions
		*out = new(bool)
		**out = **in
	}
	if in.RelayStateValidityPeriod != nil {
		in, out := &in.RelayStateValidityPeriod, &out.RelayStateValidityPeriod
		*out = new(string)
		**out = **in
	}
	if in.RateLimitAssertion != nil {
		in, out := &in.RateLimitAssertion, &out.RateLimitAssertion
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSamlSpec.
func (in *AuthSamlSpec) DeepCopy() *AuthSamlSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSamlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSmsSpec) DeepCopyInto(out *AuthSmsSpec) {
	*out = *in
	if in.OTPExpSeconds != nil {
		in, out := &in.OTPExpSeconds, &out.OTPExpSeconds
		*out = new(int32)
		**out = **in
	}
	if in.OTPLength != nil {
		in, out := &in.OTPLength, &out.OTPLength
		*out = new(int32)
		**out = **in
	}
	if in.MaxFrequency != nil {
		in, out := &in.MaxFrequency, &out.MaxFrequency
		*out = new(string)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(string)
		**out = **in
	}
	if in.Twilio != nil {
		in, out := &in.Twilio, &out.Twilio
		*out = new(AuthSmsTwilioSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSmsSpec.
func (in *AuthSmsSpec) DeepCopy() *AuthSmsSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSmsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSmsTwilioSpec) DeepCopyInto(out *AuthSmsTwilioSpec) {
	*out = *in
	out.AccountSIDRef = in.AccountSIDRef
	out.AuthTokenRef = in.AuthTokenRef
	out.MessageServiceSIDRef = in.MessageServiceSIDRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSmsTwilioSpec.
func (in *AuthSmsTwilioSpec) DeepCopy() *AuthSmsTwilioSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSmsTwilioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSmtpSpec) DeepCopyInto(out *AuthSmtpSpec) {
	*out = *in
	out.UserRef = in.UserRef
	out.PassRef = in.PassRef
	if in.SenderName != nil {
		in, out := &in.SenderName, &out.SenderName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSmtpSpec.
func (in *AuthSmtpSpec) DeepCopy() *AuthSmtpSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSmtpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthSpec) DeepCopyInto(out *AuthSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.DisableSignup != nil {
		in, out := &in.DisableSignup, &out.DisableSignup
		*out = new(bool)
		**out = **in
	}
	if in.EnableAnonymousUsers != nil {
		in, out := &in.EnableAnonymousUsers, &out.EnableAnonymousUsers
		*out = new(bool)
		**out = **in
	}
	if in.ExternalSkipNonceCheck != nil {
		in, out := &in.ExternalSkipNonceCheck, &out.ExternalSkipNonceCheck
		*out = new(bool)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(AuthEmailSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(AuthPhoneSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OAuth != nil {
		in, out := &in.OAuth, &out.OAuth
		*out = new(AuthOAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SMS != nil {
		in, out := &in.SMS, &out.SMS
		*out = new(AuthSmsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MFA != nil {
		in, out := &in.MFA, &out.MFA
		*out = new(AuthMfaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SAML != nil {
		in, out := &in.SAML, &out.SAML
		*out = new(AuthSamlSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthSpec.
func (in *AuthSpec) DeepCopy() *AuthSpec {
	if in == nil {
		return nil
	}
	out := new(AuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentProbes) DeepCopyInto(out *ComponentProbes) {
	*out = *in
	if in.Startup != nil {
		in, out := &in.Startup, &out.Startup
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Readiness != nil {
		in, out := &in.Readiness, &out.Readiness
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Liveness != nil {
		in, out := &in.Liveness, &out.Liveness
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentProbes.
func (in *ComponentProbes) DeepCopy() *ComponentProbes {
	if in == nil {
		return nil
	}
	out := new(ComponentProbes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentSpec) DeepCopyInto(out *ComponentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = new(ComponentProbes)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentSpec.
func (in *ComponentSpec) DeepCopy() *ComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.DBName != nil {
		in, out := &in.DBName, &out.DBName
		*out = new(string)
		**out = **in
	}
	out.PasswordRef = in.PasswordRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Function) DeepCopyInto(out *Function) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Function.
func (in *Function) DeepCopy() *Function {
	if in == nil {
		return nil
	}
	out := new(Function)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Function) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionList) DeepCopyInto(out *FunctionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Function, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionList.
func (in *FunctionList) DeepCopy() *FunctionList {
	if in == nil {
		return nil
	}
	out := new(FunctionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FunctionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionProjectRef) DeepCopyInto(out *FunctionProjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionProjectRef.
func (in *FunctionProjectRef) DeepCopy() *FunctionProjectRef {
	if in == nil {
		return nil
	}
	out := new(FunctionProjectRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionSpec) DeepCopyInto(out *FunctionSpec) {
	*out = *in
	out.ProjectRef = in.ProjectRef
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionSpec.
func (in *FunctionSpec) DeepCopy() *FunctionSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionStatus) DeepCopyInto(out *FunctionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionStatus.
func (in *FunctionStatus) DeepCopy() *FunctionStatus {
	if in == nil {
		return nil
	}
	out := new(FunctionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunctionsSpec) DeepCopyInto(out *FunctionsSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.VerifyJWT != nil {
		in, out := &in.VerifyJWT, &out.VerifyJWT
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunctionsSpec.
func (in *FunctionsSpec) DeepCopy() *FunctionsSpec {
	if in == nil {
		return nil
	}
	out := new(FunctionsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayListenerSpec) DeepCopyInto(out *GatewayListenerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayListenerSpec.
func (in *GatewayListenerSpec) DeepCopy() *GatewayListenerSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayListenerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]GatewayListenerSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSpec) DeepCopyInto(out *GlobalSpec) {
	*out = *in
	if in.AdditionalRedirectURLs != nil {
		in, out := &in.AdditionalRedirectURLs, &out.AdditionalRedirectURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JWTExpirySeconds != nil {
		in, out := &in.JWTExpirySeconds, &out.JWTExpirySeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSpec.
func (in *GlobalSpec) DeepCopy() *GlobalSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetaSpec) DeepCopyInto(out *MetaSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetaSpec.
func (in *MetaSpec) DeepCopy() *MetaSpec {
	if in == nil {
		return nil
	}
	out := new(MetaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OAuthProviderSpec) DeepCopyInto(out *OAuthProviderSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ClientIDRef != nil {
		in, out := &in.ClientIDRef, &out.ClientIDRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OAuthProviderSpec.
func (in *OAuthProviderSpec) DeepCopy() *OAuthProviderSpec {
	if in == nil {
		return nil
	}
	out := new(OAuthProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Project) DeepCopyInto(out *Project) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Project.
func (in *Project) DeepCopy() *Project {
	if in == nil {
		return nil
	}
	out := new(Project)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Project) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectList) DeepCopyInto(out *ProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Project, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectList.
func (in *ProjectList) DeepCopy() *ProjectList {
	if in == nil {
		return nil
	}
	out := new(ProjectList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectSpec) DeepCopyInto(out *ProjectSpec) {
	*out = *in
	in.Global.DeepCopyInto(&out.Global)
	in.Gateway.DeepCopyInto(&out.Gateway)
	in.Database.DeepCopyInto(&out.Database)
	if in.Studio != nil {
		in, out := &in.Studio, &out.Studio
		*out = new(StudioSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Rest != nil {
		in, out := &in.Rest, &out.Rest
		*out = new(RestSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Realtime != nil {
		in, out := &in.Realtime, &out.Realtime
		*out = new(RealtimeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Meta != nil {
		in, out := &in.Meta, &out.Meta
		*out = new(MetaSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = new(FunctionsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectSpec.
func (in *ProjectSpec) DeepCopy() *ProjectSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStatus) DeepCopyInto(out *ProjectStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStatus.
func (in *ProjectStatus) DeepCopy() *ProjectStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RealtimeSpec) DeepCopyInto(out *RealtimeSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RealtimeSpec.
func (in *RealtimeSpec) DeepCopy() *RealtimeSpec {
	if in == nil {
		return nil
	}
	out := new(RealtimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestSpec) DeepCopyInto(out *RestSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.DBSchemas != nil {
		in, out := &in.DBSchemas, &out.DBSchemas
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DBMaxRows != nil {
		in, out := &in.DBMaxRows, &out.DBMaxRows
		*out = new(int32)
		**out = **in
	}
	if in.DBExtraSearchPath != nil {
		in, out := &in.DBExtraSearchPath, &out.DBExtraSearchPath
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestSpec.
func (in *RestSpec) DeepCopy() *RestSpec {
	if in == nil {
		return nil
	}
	out := new(RestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageFileSpec) DeepCopyInto(out *StorageFileSpec) {
	*out = *in
	if in.VolumeClaimTemplate != nil {
		in, out := &in.VolumeClaimTemplate, &out.VolumeClaimTemplate
		*out = new(VolumeClaimTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageFileSpec.
func (in *StorageFileSpec) DeepCopy() *StorageFileSpec {
	if in == nil {
		return nil
	}
	out := new(StorageFileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageS3Spec) DeepCopyInto(out *StorageS3Spec) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(string)
		**out = **in
	}
	if in.ForcePathStyle != nil {
		in, out := &in.ForcePathStyle, &out.ForcePathStyle
		*out = new(bool)
		**out = **in
	}
	out.AccessKeyRef = in.AccessKeyRef
	out.SecretKeyRef = in.SecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageS3Spec.
func (in *StorageS3Spec) DeepCopy() *StorageS3Spec {
	if in == nil {
		return nil
	}
	out := new(StorageS3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(string)
		**out = **in
	}
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.TenantID != nil {
		in, out := &in.TenantID, &out.TenantID
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(StorageFileSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(StorageS3Spec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudioAISpec) DeepCopyInto(out *StudioAISpec) {
	*out = *in
	if in.OpenAIApiKeyRef != nil {
		in, out := &in.OpenAIApiKeyRef, &out.OpenAIApiKeyRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StudioAISpec.
func (in *StudioAISpec) DeepCopy() *StudioAISpec {
	if in == nil {
		return nil
	}
	out := new(StudioAISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudioSnippetsSpec) DeepCopyInto(out *StudioSnippetsSpec) {
	*out = *in
	if in.VolumeClaimTemplate != nil {
		in, out := &in.VolumeClaimTemplate, &out.VolumeClaimTemplate
		*out = new(VolumeClaimTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StudioSnippetsSpec.
func (in *StudioSnippetsSpec) DeepCopy() *StudioSnippetsSpec {
	if in == nil {
		return nil
	}
	out := new(StudioSnippetsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StudioSpec) DeepCopyInto(out *StudioSpec) {
	*out = *in
	in.ComponentSpec.DeepCopyInto(&out.ComponentSpec)
	if in.DefaultOrganization != nil {
		in, out := &in.DefaultOrganization, &out.DefaultOrganization
		*out = new(string)
		**out = **in
	}
	if in.DefaultProject != nil {
		in, out := &in.DefaultProject, &out.DefaultProject
		*out = new(string)
		**out = **in
	}
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(StudioAISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Snippets != nil {
		in, out := &in.Snippets, &out.Snippets
		*out = new(StudioSnippetsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StudioSpec.
func (in *StudioSpec) DeepCopy() *StudioSpec {
	if in == nil {
		return nil
	}
	out := new(StudioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeClaimTemplateSpec) DeepCopyInto(out *VolumeClaimTemplateSpec) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeClaimTemplateSpec.
func (in *VolumeClaimTemplateSpec) DeepCopy() *VolumeClaimTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(VolumeClaimTemplateSpec)
	in.DeepCopyInto(out)
	return out
}
