{{- if .Values.deployment.kong.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supabase.kong.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
data:
  kong-entrypoint.sh: |{{ .Files.Get "files/kong/kong-entrypoint.sh" | nindent 4 }}
  kong.yml: |{{ tpl (.Files.Get "files/kong/kong.yml") . | nindent 4 }}
{{- end }}
