{{- define "supabase.secret.analytics.name" -}}
{{- if .Values.secret.analytics.secretRef -}}
{{- .Values.secret.analytics.secretRef -}}
{{- else -}}
{{- include "supabase.secret.analytics" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.analytics.key.publicAccessToken" -}}
{{- index (default (dict) .Values.secret.analytics.secretRefKey) "publicAccessToken" | default "publicAccessToken" -}}
{{- end -}}

{{- define "supabase.secret.analytics.key.privateAccessToken" -}}
{{- index (default (dict) .Values.secret.analytics.secretRefKey) "privateAccessToken" | default "privateAccessToken" -}}
{{- end -}}

{{- if not .Values.secret.analytics.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.analytics" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  publicAccessToken: {{ .Values.secret.analytics.publicAccessToken | b64enc | quote }}
  privateAccessToken: {{ .Values.secret.analytics.privateAccessToken | b64enc | quote }}
{{- end }}
