{{- if not .Values.secret.analytics.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.analytics" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  publicAccessToken: {{ .Values.secret.analytics.publicAccessToken | b64enc | quote }}
  privateAccessToken: {{ .Values.secret.analytics.privateAccessToken | b64enc | quote }}
{{- end }}
