{{- if not .Values.secret.apikey.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.apikey" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  publishableKey: {{ .Values.secret.apikey.publishableKey | b64enc | quote }}
  secretKey: {{ .Values.secret.apikey.secretKey | b64enc | quote }}
  anonKeyAsymmetric: {{ .Values.secret.apikey.anonKeyAsymmetric | b64enc | quote }}
  serviceRoleKeyAsymmetric: {{ .Values.secret.apikey.serviceRoleKeyAsymmetric | b64enc | quote }}
  jwtKeys: {{ .Values.secret.apikey.jwtKeys | b64enc | quote }}
  jwtJwks: {{ .Values.secret.apikey.jwtJwks | b64enc | quote }}
{{- end }}
