{{- define "supabase.secret.apikey.name" -}}
{{- if .Values.secret.apikey.secretRef -}}
{{- .Values.secret.apikey.secretRef -}}
{{- else -}}
{{- include "supabase.secret.apikey" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.apikey.key.publishableKey" -}}
{{- index (default (dict) .Values.secret.apikey.secretRefKey) "publishableKey" | default "publishableKey" -}}
{{- end -}}

{{- define "supabase.secret.apikey.key.secretKey" -}}
{{- index (default (dict) .Values.secret.apikey.secretRefKey) "secretKey" | default "secretKey" -}}
{{- end -}}

{{- define "supabase.secret.apikey.key.anonKeyAsymmetric" -}}
{{- index (default (dict) .Values.secret.apikey.secretRefKey) "anonKeyAsymmetric" | default "anonKeyAsymmetric" -}}
{{- end -}}

{{- define "supabase.secret.apikey.key.serviceRoleKeyAsymmetric" -}}
{{- index (default (dict) .Values.secret.apikey.secretRefKey) "serviceRoleKeyAsymmetric" | default "serviceRoleKeyAsymmetric" -}}
{{- end -}}

{{- define "supabase.secret.apikey.key.jwtKeys" -}}
{{- index (default (dict) .Values.secret.apikey.secretRefKey) "jwtKeys" | default "jwtKeys" -}}
{{- end -}}

{{- define "supabase.secret.apikey.key.jwtJwks" -}}
{{- index (default (dict) .Values.secret.apikey.secretRefKey) "jwtJwks" | default "jwtJwks" -}}
{{- end -}}

{{- if not .Values.secret.apikey.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.apikey" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  publishableKey: {{ .Values.secret.apikey.publishableKey | b64enc | quote }}
  secretKey: {{ .Values.secret.apikey.secretKey | b64enc | quote }}
  anonKeyAsymmetric: {{ .Values.secret.apikey.anonKeyAsymmetric | b64enc | quote }}
  serviceRoleKeyAsymmetric: {{ .Values.secret.apikey.serviceRoleKeyAsymmetric | b64enc | quote }}
  jwtKeys: {{ .Values.secret.apikey.jwtKeys | b64enc | quote }}
  jwtJwks: {{ .Values.secret.apikey.jwtJwks | b64enc | quote }}
{{- end }}
