{{- if and .Values.bigQuery.enabled (not .Values.secret.bigquery.secretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.bigquery" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  gcloud.json: {{ .Values.secret.bigquery.gcloudJson | b64enc | quote }}
{{- end }}
