{{- if not .Values.secret.db.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.db" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secret.db.password | b64enc | quote }}
  database: {{ .Values.secret.db.database | b64enc | quote }}
  password_encoded: {{ .Values.secret.db.password | urlquery | b64enc | quote }}
{{- end }}
