{{- if not .Values.secret.jwt.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.jwt" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  anonKey: {{ .Values.secret.jwt.anonKey | b64enc | quote }}
  serviceKey: {{ .Values.secret.jwt.serviceKey | b64enc | quote }}
  secret: {{ .Values.secret.jwt.secret | b64enc | quote }}
{{- end }}
