{{- define "supabase.secret.meta.name" -}}
{{- if .Values.secret.meta.secretRef -}}
{{- .Values.secret.meta.secretRef -}}
{{- else -}}
{{- include "supabase.secret.meta" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.meta.key.cryptoKey" -}}
{{- index (default (dict) .Values.secret.meta.secretRefKey) "cryptoKey" | default "cryptoKey" -}}
{{- end -}}

{{- if not .Values.secret.meta.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.meta" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  cryptoKey: {{ .Values.secret.meta.cryptoKey | b64enc | quote }}
{{- end }}
