{{- if not .Values.secret.meta.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.meta" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  cryptoKey: {{ .Values.secret.meta.cryptoKey | b64enc | quote }}
{{- end }}
