{{- if not .Values.secret.minio.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.minio" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.secret.minio.user | b64enc | quote }}
  password: {{ .Values.secret.minio.password | b64enc | quote }}
{{- end }}
