{{- define "supabase.secret.minio.name" -}}
{{- if .Values.secret.minio.secretRef -}}
{{- .Values.secret.minio.secretRef -}}
{{- else -}}
{{- include "supabase.secret.minio" . -}}
{{- end -}}
{{- end -}}

{{- define "supabase.secret.minio.key.user" -}}
{{- index (default (dict) .Values.secret.minio.secretRefKey) "user" | default "user" -}}
{{- end -}}

{{- define "supabase.secret.minio.key.password" -}}
{{- index (default (dict) .Values.secret.minio.secretRefKey) "password" | default "password" -}}
{{- end -}}

{{- if not .Values.secret.minio.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.minio" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.secret.minio.user | b64enc | quote }}
  password: {{ .Values.secret.minio.password | b64enc | quote }}
{{- end }}
