{{- if not .Values.secret.s3.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.s3" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  keyId: {{ .Values.secret.s3.keyId | b64enc | quote }}
  accessKey: {{ .Values.secret.s3.accessKey | b64enc | quote }}
{{- end }}
