{{- if not .Values.secret.smtp.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.secret.smtp" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.secret.smtp.username | b64enc | quote }}
  password: {{ .Values.secret.smtp.password | b64enc | quote }}
{{- end }}
