{{- if .Values.deployment.meta.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.meta.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- with .Values.deployment.meta.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.meta.enabled }}
  replicas: {{ .Values.deployment.meta.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.meta.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "supabase.meta.selectorLabels" . | nindent 8 }}
      {{- with .Values.deployment.meta.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "supabase.meta.serviceAccountName" . }}
      {{- if hasKey .Values.deployment.meta "automountServiceAccountToken" }}
      automountServiceAccountToken: {{ .Values.deployment.meta.automountServiceAccountToken }}
      {{- end }}
      restartPolicy: Always
      {{- if hasKey .Values.deployment.meta "terminationGracePeriodSeconds" }}
      terminationGracePeriodSeconds: {{ .Values.deployment.meta.terminationGracePeriodSeconds }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.deployment.meta.podSecurityContext | nindent 8 }}
      {{- with .Values.image.meta.pullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.meta.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.meta.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.meta.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.meta.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: {{ include "supabase.meta.name" $ }}
          image: "{{ .Values.image.meta.repository }}:{{ .Values.image.meta.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.meta.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            {{- range $key, $value := .Values.environment.meta }}
            {{- if and (ne $key "DB_HOST") (ne $key "DB_PORT") }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- include "supabase.db.hostEnv" (dict "root" . "name" "DB_HOST") | nindent 12 }}
            {{- include "supabase.db.portEnv" (dict "root" . "name" "DB_PORT") | nindent 12 }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.password" . }}
            - name: DB_NAME
              {{- if and .Values.secret.db.secretRef (not (hasKey (default (dict) .Values.secret.db.secretRefKey) "database")) }}
              value: {{ .Values.secret.db.database | default "postgres" | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.db.name" . }}
                  key: {{ include "supabase.secret.db.key.database" . }}
              {{- end }}
            - name: PG_META_DB_HOST
              value: $(DB_HOST)
            - name: PG_META_DB_PORT
              value: $(DB_PORT)
            - name: PG_META_DB_NAME
              value: $(DB_NAME)
            - name: PG_META_DB_USER
              value: $(DB_USER)
            - name: PG_META_DB_PASSWORD
              value: $(DB_PASSWORD)
            - name: PG_META_DB_SSL_MODE
              value: $(DB_SSL)
            - name: CRYPTO_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.secret.meta.name" . }}
                  key: {{ include "supabase.secret.meta.key.cryptoKey" . }}
          {{- with .Values.deployment.meta.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.meta.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.meta.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.meta.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.meta.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.meta.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.meta.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.deployment.meta.securityContext | nindent 12 }}
      {{- with .Values.deployment.meta.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
