apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: supabase-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-db
          image: supabase/postgres:17.6.1.084
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Copying init scripts into existing image script directory..."
              cp -r /docker-entrypoint-initdb.d/* /initdb.d/
              cp /custom-init-scripts/98-webhooks.sql /initdb.d/init-scripts/
              cp /custom-init-scripts/99-roles.sql /initdb.d/init-scripts/
              cp /custom-init-scripts/99-jwt.sql /initdb.d/init-scripts/

              cp /custom-init-scripts/99-logs.sql /initdb.d/migrations/
              cp /custom-init-scripts/99-realtime.sql /initdb.d/migrations/
              cp /custom-init-scripts/97-_supabase.sql /initdb.d/migrations/
              cp /custom-init-scripts/99-pooler.sql /initdb.d/migrations/

              echo "Initialization scripts are ready"
          volumeMounts:
            - mountPath: /custom-init-scripts
              name: custom-init-scripts
            - mountPath: /initdb.d
              name: initdb-scripts-data
      containers:
        - name: postgres
          image: supabase/postgres:17.6.1.084
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              value: "/var/run/postgresql"
            - name: PGPORT
              value: "5432"
            - name: POSTGRES_PORT
              value: "5432"
            - name: JWT_EXP
              value: "3600"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-db-credentials
                  key: password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-db-credentials
                  key: password
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: supabase-db-credentials
                  key: database
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: supabase-db-credentials
                  key: database
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-jwt-credentials
                  key: secret
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb-scripts-data
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume
              subPath: postgres-data
          lifecycle:
            preStop:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "pg_ctl -D /var/lib/postgres/data -w -t 60 -m fast stop",
                  ]
      volumes:
        - name: initdb-scripts-data
          emptyDir: {}
        - name: custom-init-scripts
          configMap:
            name: initdb
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: supabase-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
