apiVersion: v1
kind: Secret
metadata:
  name: supabase-db-credentials
  namespace: supabase-postgres
type: Opaque
stringData:
  password: "your-super-secret-and-long-postgres-password"
  database: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-db-credentials
  namespace: default
type: Opaque
stringData:
  password: "your-super-secret-and-long-postgres-password"
  database: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: supabase-jwt-credentials
  namespace: supabase-postgres
type: Opaque
stringData:
  secret: "your-super-secret-jwt-token-with-at-least-32-characters-long"
